config/routes.rb
AdelBlog::Application.routes.draw do

  get "users/create"
  get "users/:id/edit" => 'users#show', as: :edit_user
  get 'user/:id' => 'users#show', as: :user
  get 'users' => 'users#index', as: :user_index
  devise_for :users
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  resources :articles 
  resources :categories
  
 

end

app/models/article.rb
class Article < ActiveRecord::Base
belongs_to :user
validates :title, presence: true, length: { minimum: 3, maximum: 50}
validates :description, presence: true, length: {minimim: 10, maximum: 2000 }
validates :user_id, presence: true

	
  def self.search(search)
	  where("title LIKE ?", "%#{search}%") 
	  where("description LIKE ?", "%#{search}%")
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :articles
	validates :name, presence: true, length: { minimum: 3, maximum: 25}
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 

  has_many :articles
  before_save { self.email = email.downcase }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_attached_file :avatar,
	styles: { medium: "200x300>", thumb: "100x100>" },
	default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?
  

  protected

  def configure_devise_permitted_parameters
    registration_params = [:username, :first_name,:last_name, :address,:gender, :DOB, :email, :password, :password_confirmation, :avatar, :thumb, :medium, :search]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :add_current_user, axcept: [:index]



	def index
		if params[:search]	
			@articles= Article.search(params[:search]).order("created_at DESC")
		else
			@articles= Article.all.order('created_at DESC')
		end
			@articles= Article.paginate(:page => params[:page], :per_page => 2)	
	end

	def new
		@article=Article.new
	end

	def edit
	end


	def create
		@article=Article.new(article_params)
		@article.user=current_user
		if @article.save
		flash[:success] = "Article was successfully created"
		redirect_to article_path(@article)
		else
		render 'new'
		end
	end

	def update
		if @article.update(article_params)
		flash[:success]= "Article was successfully updated"
		redirect_to article_path(@article)
		else 
		render 'edit'
		end
	end	

	def show
	end

	def destroy
		
		flash[:danger] = "article was successfully deleted"
		redirect_to article_path
	end



	private 
	def set_article
		@article = Article.find(params[:id])
	end

		def article_params
		params.require(:article).permit(:title, :description)
	end

	def add_current_user
		unless user_signed_in?
			
			redirect_to user_session_path
			flash[:danger] = "please sign in"
		end
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_login, axcept: [:index]

	def index
		@categories=Category.all
	end

	def show
	end

	def new
		@category= Category.new
	end

	def create
		@category=Category.new(category_params)
      if @category.save
      flash[:success] = "category was created successfully"
      redirect_to categories_path
    
      else
    render 'new'
      end
	end

	private
    def category_params
    params.require(:category).permit(:name)
  end

		def require_login
    unless current_user
      redirect_to user_session_path
      flash[:danger] = "Please login first"
    end
  end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index

    @users= User.all.paginate(:page => params[:page], :per_page => 5)
  end 

  def create
  	@user=User.new(user_params)
      if @user.save
    flash[:success] = "Welcome to Adel blog #{@user.username}"
      else
    render 'new'
      end
  end

  def edit
  	 @user= User.find(params[:id])
  end

  def show
  	@user= User.find(params[:id])

    @user_articles= @user.articles.paginate(:page => params[:page], :per_page => 5)

  end
  private
    def user_params
    params.require(:user).permit(:username, :email, :password)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	 def home

	 end

	 def about

	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class=" col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
  
          <div class="article-body">
            <%= truncate(article.description, length: 100) %>
            <div class= "article-details">
              <small>created by: <%= article.user.username if article.user%>
                <%= time_ago_in_words(article.created_at)%> ago,
                last update: <%= time_ago_in_words(article.updated_at)%> ago
              </small>
            </div>
          </div>
            <div class= "article-actions">
              <% if current_user.admin? %>
              <%= link_to " edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>  
              <%end %>   
            </div>
          </div>
      </div>
    </div>
 <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class= 'row'>
	<div class= 'col-xs-12'>
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class= "form-group">
				<div class= "control-lable col-sm-2">
					<%= f.label :title %>
				</div>
				<div class= "col-sm-8">
				<%= f.text_field :title, class: "form-control", placeholder: "Title of aticle", autofocus: true %>
				</div>
		</div>
		<div class= "form-group">
				<div class= "control-lable col-sm-2">
					<%= f.label :description %>
				</div>
				<div class= "col-sm-8">
					<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
				</div>
			</div>
				<div class= "form-group">
					<div class= "col-sm-offset-2 col-sm-10">
						<%= f.submit class: 'btn btn-primary btn-lg'%>
					</div>
				</div>
	<% end %>
	<div class= "col-xs-4 col-xs-offset-4">
		[ <%= link_to "Cancel request and return to articles.", articles_path %> ]
	</div>
		</div>
	</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">listing all articles</h1>
<div align="center">
	<%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
	<%= will_paginate @posts %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article: </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align= "center">Title: <%= @article.title %></h2>
	<div class= "well col-xs-8 col-xs-offset-2">
		<h4 class= "center description"><strong>Description:</strong></h4>
		<h3 align= "center" class= "center description">created by: </h3>
		<ul class= "listing">
			<div class= "row">
				<div align= "center">
					<li class="round-image-50" ><%= link_to image_tag(current_user.avatar.url(:thumb))%></li>
					<li> <%= link_to current_user.username, user_path(current_user)%></li>
					<li class="article-title">
						<%= link_to @article.user.username, user_path(@article.user) %>
					</li>
					<li><small>
						<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
					</small></li>
				</div>
			</div>
		</ul>

			<hr><%= simple_format(@article.description) %>
				<div class= "article-actions">
					<%= link_to " edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
					<%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>
					<%= link_to "View all articles ", articles_path, class: "btn btn-xs btn-success" %>
				</div>
	</div>

app/views/categories/index.html.erb
<h1 align="center">listing all Categories: </h1>
<% @categories.each do |category| %>
<ul class= "listing" align="center">
    <div class="row">
      <div class = "well col-md-4 col-md-offset-4">
        <li class= "article_title">
          <%= link_to "#{category.name}", category_path(category) %>
        </li>
      </div>
    </div>
  </ul>
  <% end %>
  

app/views/categories/new.html.erb
<%= render 'shared/errors', obj: @category%>
<%if current_user.admin? %>
	<h1 align="center">Create new category:</h1>
		<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class= "form-group">
				<div class= "control-lable col-sm-2">
					<%= f.label :name %>
				</div>
					<div class= "col-sm-8">
						<%= f.text_field :name, class: "form-control", placeholder: "category name", autofocus: true %>
					</div>
			</div>
			<div class= "form-group">
				<div class= "col-sm-offset-2 col-sm-10">
					<%= f.submit class: 'btn btn-primary btn-lg'%>
				</div>
			</div>
		<%end%>
		<%else %>
		<h2 align= "center">you cannot access this page you don't have permission</h2>
<%end%>
<div class= "col-xs-4 col-xs-offset-4">
		[ <%= link_to "Cancel request and return to articles.", articles_path %> ]
	</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyrights &copy;2016, All Rights Reseved  by <a href="https://www.facebook.com/adel.almaleh2">Adel Almaleh</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Articles", articles_path %></li>
				<li><%= link_to "New article", new_article_path %></li>
				<li><%= link_to "Terms", '#' %></li>
				<li><%= link_to "Privacy", '#' %></li>
				<li><%= link_to "Support", '#' %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class= "row">
	<div class = "col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%="#{name}" %>'>
				<a href="#" class=“close” data-dismiss=“alert”>&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)  %>
			</div>
		<%end%>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "adel blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path%></li>
        <li><%= link_to "Users", user_index_path%></li>

          <%if user_signed_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
            <% end %>
          </li>

        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user && current_user.admin? %>
              <li><%= link_to "new Category", new_category_path %></li>
              <%end %>
              <li><%= link_to "All Categories", categories_path %></li>
              <li role="separator" class="divider"></li>
              <% Category.all.each do |category|%>
              <li><%= link_to "#{category.name}", category_path(category) %></a></li>
              <%end %>
            </ul>
          </li>
        
      </ul>
        
        <%= form_tag(articles_path, :method => "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search " %>
        <%= submit_tag "Search" %>
        <% end %>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user  %>
          <li class="round-image-50" >
            <%= link_to image_tag(current_user.avatar.url(:thumb)) %>
          </li>
          <li>
            <%= link_to current_user.username, user_path(current_user), id: "username"%>
          </li> 
          
         
        <% else %>
          <li><%= link_to "Sign in", user_session_path %></li>
        <% end %>
       

        <%if user_signed_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><%= link_to "view your profile", user_path(current_user) %>
              <li><%= link_to "Edit your profile", edit_user_registration_path %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path,:method => :delete %>
            </ul>
            <% end %>
          </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdelBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<%= render 'layouts/messages' %>
	<div class= "container">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class=	"row">
	<div class= “col-xs-8 col-xs-offset-2”>
		<div class= "panel panel-danger">
			<div class= "panel-heading">
				<h2 class= "panel-title">
					<%= pluralize(obj.errors.count, "error")%>
					prohibited this article from being saved:
				</h2>
				<div class= "panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1 align= "center"> All Bloggers</h1>
<div align= "center">
	<%= will_paginate @articles %>
	<% @users.each do |user| %>
		<ul class= "listing">
			<div class= "row">
				<div class= "well col-md-4 col-md-offset-4">
					<li class="round-image-50" ><%= link_to image_tag(user.avatar.url(:thumb))%></li>
					<li> <%= link_to current_user.username, user_path(current_user)%></li>
					<li class="article-title">
						<%= link_to user.username, user_path(user) %>
					</li>
					<li><small><%= pluralize(user.articles.count, "article") if user.articles %></small>
					</li>
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/users/show.html.erb
<h1 class= "text">Welcome to <%= @user.username %>'s page</h1>
<li align= "center" ><%= image_tag(current_user.avatar.url(:medium)) %></li>
<h2 class= "text"><%= @user.username %>'s Articles</h2>

<div align= "center">
	<%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>


<div align= "center">
	<%= will_paginate @user_articles%>
</div>

app/views/welcome/about.html.erb
<h1>hello this is about page</h2>

	<%= link_to "Home", root_path %>

app/views/welcome/home.html.erb
<div class=" center jumbotron">
  <h1>Adel Blog</h1>
  <%= link_to "Get Started", new_user_registration_path, class: 'btn btn-primary btn-xlarge' %>
<%= link_to "Log in", user_session_path, class: 'btn btn-primary btn-lg'%>
</div>